### ISSUE TITLE
allow server-side inputs

### ISSUE THREAD

**Issue by dchandran** [sing-group/biojs-vis-blasterjs#1]
Hi, 
Thanks for the nice project. For my use case, I have BLAST result files generated by the server. The client side code simply needs to display these results. In other words, there is no need for a file input box. I managed to get this to work using the following code, but it would be nice to have a have this be part of the API.

``` javascript
//...fetch resultsString from server
let myBlob = new Blob([resultsString], {type : "text/plain"});
let fakeEvent = {
   target: {  files: [myBlob]   }
};
instance._displayAlignments(fakeEvent, instance);
```

**Comment by abmiguez** [comment]
Hi Deepak,
Thank you very much for the feedback. You're absolutely righ , this functionality would be interesting, in the next version we will add the functionality to display the results from a string adding a new public method.
I will publish here and close up the issue when this version becomes available.
Regards,
Aitor

**Comment by abmiguez** [comment]
As with the previous one, this functionality is already in the new version.
Again, thank you very much.
Best regards,
Aitor

**Comment by telatin** [comment]
This is what I was also looking for: is there a doc page for this?
**EDIT**: I found it in the README.md, before I only checked the website, sorry!

**Comment by Aditya-Upa** [comment]
i read the README file and converted the BLAST output into a string using JSON.stringify function and fed it to the blasterjs component like so :
 var alignments = {blastResults};
    const instance = new blasterjs({
      //input: 'blastinput',
      string: alignments,
      multipleAlignments: 'blast-multiple-alignments',
      alignmentsTable: 'blast-alignments-table',
      singleAlignment: 'blast-single-alignment',
    });
  }, []);

  return (
    <div id="rootDiv">
      {/* <input id="blastinput" type="file" /> */}
      <div id="blast-multiple-alignments"></div>
      <div id="blast-alignments-table"></div>
      <div id="blast-single-alignment"></div>
    </div>
  );
  
  But upon doing this i am receiving an error of invalid blast output file format. Is this not how to use it? sorry I am new to all this so please help me out!
