### ISSUE TITLE
alignment table onclick callback

### ISSUE THREAD

**Issue by dchandran** [sing-group/biojs-vis-blasterjs#2]
Hi, 
It would be nice if I can add custom callbacks, specifically in the `onclick` method of the alignment table. After obtaining the BLAST results, the user may need to perform additional actions on those results - a callback would allow me to add this capability to my app. I added the following lines to the `butDesc.onclick` function in order to achieve this:

``` javascript
if (self.opt.callback) {
  self.opt.callback(this.alignment);
}
```

**Comment by abmiguez** [comment]
Hi Deepak,
Again, thank you very much. This would be an interesting feature, especially for users who don't want to use the third element of the library. We hope to add this functionality in the next version of the library.
I will publish here and close up the issue when this version becomes available.
Regards,
Aitor

**Comment by abmiguez** [comment]
Sorry about the delay, but we could not publish a new version while we had a publication under revision process. We have already uploaded the new version of the library with this functionality. Thank you very much for your contribution.
Best regards,
Aitor
