### ISSUE TITLE
error with browserified script

### ISSUE THREAD

**Issue by feliixx** [sing-group/biojs-vis-blasterjs#3]
Hi, 

We are facing some issues with the browserified script generated after `npm install` ( `build/blasterjs.js` ). 
We use it like this : 

        <script type="text/javascript" src="js/blasterjs.js"></script>

The module can't be recognize, the exact error is 

      ReferenceError: blasterjs is not defined

Are we missing something? Do we need to run an other command to generate the browserified script? 
thanks in advance

**Comment by feliixx** [comment]
I could solve the issue by re-generating the browserified file : 

`browserify index.js --s blasterjs > blasterjs.js`

maybe you could consider update the browserify command in package.json !

**Comment by abmiguez** [comment]
Hi Adrien,
First of all thank you very much for reporting this bug.
We have tested on different machines and we can not get the build / blasterjs.js file wrong. We have tried installing it directly with "npm install biojs-vis-blasterjs" and also cloned it from Github and running "npm install", and with both methods it generates, on all machines, the files correctly.
If you check the example on BioJS Registry (http://biojs.io/d/biojs-vis-blasterjs) also builds it correctly.
When you run the command "npm install", it must automatically run the "build" command which in turn runs "browserfy".

We will continue to test to find the source of this error.

Regards,
Aitor

**Comment by feliixx** [comment]
Thanks for the answer, I forgot to mention that we're using node version 7.1.0, npm version 3.10.9 and browserify version 13.1.1 on ubuntu 16.04

**Comment by abmiguez** [comment]
Hi Adrien, could you send to aiblanco@uvigo.es the build/blasterjs.js file that was generated erroneously with the "npm install" command?

**Comment by feliixx** [comment]
Ok it looks like the problem doesn't come from the file itself. After `npm install`, the script works fine with your example, but it throw errors in my webapp ( the same code works fine with the javascript file generated with the --s option). I'm also using JQuery 1.8.2 and spin.js ( http://spin.js.org/ ) on this page, could it be a kind of scope conflict?

**Comment by abmiguez** [comment]
No, at first there is no conflict with those two scripts. What I've checked is that with the script generated manually with Browserify this line "_var blasterjs = require (" biojs-vis-blasterjs ")_" is not required. 
If the script generated with the command "_npm install"_ was generated correctly, or you lack that line where you define blasterjs (_var blasterjs = require (" biojs-vis-blasterjs ");_), or we have to continue looking for the root of that error.
