### ISSUE TITLE
Blast score parsing error 

### ISSUE THREAD

**Issue by feliixx** [sing-group/biojs-vis-blasterjs#4]
We are using blast v 2.2.30 and we have noticed that the score value isn't parsed correctly by the module if it's above 100, because it's not formatted the same way in the blast output. 

example: 

**score <100**
```
>JK2MQ9P02HIOES 
Length=327

 Score = 89.8 bits (48),  Expect = 5e-19
 Identities = 51/52 (98%), Gaps = 1/52 (2%)
```

**score > 100**
```
>JK2MQ9P02GXIRB 
Length=78

 Score =   145 bits (78),  Expect = 1e-35
 Identities = 78/78 (100%), Gaps = 0/78 (0%)
```

if Score is higher than 100, there is 3 spaces between the '=' char and the score instead of one. 

It can be easily fixed in the `parseBlastText` method with a replace like this (line 186 of index.js) : 

`var score        = lines[currentLine+2].split(',')[0].replace(/\s\s+/g, ' ').split(' ')[3];`

If this seems ok to you I'll submit a PR

**Comment by abmiguez** [comment]
Hi Adrien and sorry for the delay,
Thank you again for reporting this bug and its solution.
I think the repository permissions should allow it, so if you want you can send a PR to fix this bug.

Best regards,
Aitor
